name: BuildTest
description: > 
  Builds and tests an installation of PyNE in a single docker image.
  This action is used for bootstrap testing when building the docker
  images as well as testing of each PR using those docker images.
inputs:
  stage:
    description: The docker stage that will be used as the docker image for testing.
    required: true
    default: ''
runs:
  using: "composite"
  steps: 
    - name: Setup Environment Variables
      shell: bash -l {0}
      run: |
        if [[ "${{ inputs.stage }}" == "moab" || "${{ inputs.stage }}" == "dagmc" ]]; then
          echo "MOAB_ROOT=/root/opt/moab" >> $GITHUB_ENV
        fi
        if [[ "${{ inputs.stage }}" == "dagmc" ]]; then
          echo "DAGMC_ROOT=/root/opt/dagmc" >> $GITHUB_ENV
        fi
        export ADD_FLAG="${ADD_FLAG} "
        echo "ADD_FLAG=${ADD_FLAG}" >> $GITHUB_ENV
        
    - name: Building PyNE
      shell: bash -l {0}
      run: |
        cd $GITHUB_WORKSPACE
        pip3 install .
        export PATH="$PATH:/github/home/.local/bin"
        cd ..
        nuc_data_make

    - name: Testing PyNE
      shell: bash -l {0}
      run: |
        cd $GITHUB_WORKSPACE/tests
        ./ci-run-tests.sh python3