# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Hi, and welcome to PyNE!  :wave: Thanks for opening your first issue.  We recommend that you 
  include information such as the version of PyNE you're working with (eg, develop branch or 
  a specific version), the platform you are operating on, the expected behavior, and the actual 
  behavior you are bringing our attention to. The more deatil you provide, the better others in 
  this community will be able to help you.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Hi!  Welcome, and thanks for opening this pull request.  We ask that you follow our 
  template for new pull requests, and soon you'll hear back about the results of our tests and
  continuous integration checks.  Thank you for your contribution!

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Hooray!  Congratulations on your first merged pull request!  We hope we keep
  seeing you around! If you haven't already, consider joining our 
  [User's Group](https://groups.google.com/forum/#!forum/pyne-users) and 
  our [Development List](https://groups.google.com/forum/#!forum/pyne-dev). :fireworks:

# It is recommend to include as many gifs and emojis as possible
