"""Tests the part of dtypes that is accessible from Python."""
###################
###  WARNING!!! ###
###################
# This file has been autogenerated
from __future__ import print_function


from numpy.testing import assert_array_equal, assert_array_almost_equal

import os
import numpy as np

from pyne import dtypes

