#!/bin/bash
cd lapack_routine
ifort -c -O3  dlamch.f  
ifort -c -O3  ieeeck.f  
ifort -c -O3  ilaenv.f  
ifort -c -O3  iparmq.f
ifort -c -O3  lsame.f
ifort -c -O3  xerbla.f
mv *o ../
cd ../double
ifort -c -O3  dtrsm.f
ifort -c -O3  dgesv.f
ifort -c -O3  dgetf2.f
ifort -c -O3  dgetrf.f
ifort -c -O3  dgetrs.f
ifort -c -O3  dlaswp.f
ifort -c -O3  idamax.f
ifort -c -O3  dswap.f
ifort -c -O3  dscal.f
ifort -c -O3  dger.f
ifort -c -O3  dgemm.f
ifort -c -O3  dgemv.f
ifort -c -O3  dsysv.f
ifort -c -O3  dposv.f
ifort -c -O3  dpotrs.f
ifort -c -O3  dpotrf.f
ifort -c -O3  dsytrf.f
ifort -c -O3  dsytrs.f
ifort -c -O3  dsytrs2.f
ifort -c -O3  dsyrk.f
ifort -c -O3  dpotf2.f
ifort -c -O3  dlasyf.f
ifort -c -O3  dsytf2.f
ifort -c -O3  dsytrs2.f
ifort -c -O3  dsyconv.f
ifort -c -O3  dcopy.f
ifort -c -O3  ddot.f
ifort -c -O3  disnan.f
ifort -c -O3  dsyr.f
ifort -c -O3  dlaisnan.f
mv *o ../
cd ../
ar rc lapack.a *.o
rm *o

