#! /bin/bash
#
#gfortran -c -fdefault-real-8 invar.f90
#gfortran -c -fdefault-real-8 solvar.f90
#gfortran -c -fdefault-real-8 ll_module.f90
#gfortran -c -fdefault-real-8 timevar.f90
#gfortran -c -fdefault-real-8 main.f90
#gfortran -c -fdefault-real-8 version.f90
#gfortran -c -fdefault-real-8 input.f90
#gfortran -c -fdefault-real-8 angle.f90
#gfortran -c -fdefault-real-8 readmt.f90
#gfortran -c -fdefault-real-8 readxs.f90
#gfortran -c -fdefault-real-8 readsrc.f90
#gfortran -c -fdefault-real-8 read_inflow.f90
#gfortran -c -fdefault-real-8 check.f90
#gfortran -c -fdefault-real-8 echo.f90
#gfortran -c -fdefault-real-8 solve.f90
#gfortran -c -fdefault-real-8 inner.f90
#gfortran -c -fdefault-real-8 sweep.f90
#gfortran -c -fdefault-real-8 output.f90
#gfortran -c -fdefault-real-8 output_phi.f90
#gfortran -o ../LL.exe *.o lapack.a
#rm *.o *.mod
gfortran -fPIC -c invar.f90
gfortran -fPIC -c solvar.f90
gfortran -fPIC -c timevar.f90
f2py -m main -c invar.o main.f90 read_inflow.f90 readmt.f90 readxs.f90 readsrc.f90 check.f90 angle.f90 solvar.o timevar.o solve.f90 inner.f90 sweep.f90 ll_module.f90 output.f90 echo.f90
