#! /bin/bash
#
#gfortran -fPIC -c invar.f90
#gfortran -fPIC -c solvar.f90
#gfortran -fPIC -c timevar.f90
#gfortran -fPIC -c ahotn_kernel_module.f90, solve.f90, inner_ahotn_l.f90
gfortran -fPIC -c *.f90
rm main.o
f2py -m main -c *.o main.f90 -lblas -llapack
#-L./blas/ =L./lapack/double/ -L./lapack/util -lmini_blas_s -lmini_lapack_util_s -lmini_lapack_D_s
#f2py -m main -c invar.o solvar.o main.f90 read_inflow.f90 readmt.f90 readxs.f90 readsrc.f90 check.f90 angle.f90 timevar.o solve.o inner_ahotn_l.o sweep.o ahotn_kernel_module.o output.f90

#f2py -m input -c invar.o input.f90 read_inflow.f90 readmt.f90 readxs.f90 readsrc.f90 check.f90 angle.f90
#f2py -m solve -c invar.o solvar.o timevar.o solve.f90 inner.f90 sweep.f90 lin_nodal_module.f90
#f2py -m output -c invar.o solvar.o output.f90


#-L./blas/ -L./lapack/double
#-L./../../lapack_dependency/double/dgesv.f
