################################################
#                 WARNING!                     #
# This file has been auto-generated by xdress. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################


from libcpp.vector cimport vector as cpp_vector

# function signatures
cdef extern from "source_sampling.h" :

    void mcnp_sampling_setup_() except +



# function signatures
cdef extern from "source_sampling.h" :

    cpp_vector[double] pyparticle_birth_() except +
    cpp_vector[double] pyparticle_birth_(cpp_vector[double]) except +




{'cpppxd_footer': '', 'pyx_header': '', 'pxd_header': '', 'pxd_footer': '', 'cpppxd_header': '', 'pyx_footer': ''}