################################################
#                 WARNING!                     #
# This file has been auto-generated by xdress. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################


from libcpp.string cimport string as std_string
from libcpp.vector cimport vector as cpp_vector
from pyne cimport cpp_endf2

cdef extern from "endf.h" namespace "pyne":

    cdef cppclass endf_id:
        # constructors
        endf_id() except +

        # attributes
        int mat
        int mf
        int mt

        # methods

        pass



cdef extern from "endf_mt.h" namespace "pyne":

    cdef cppclass mt_base:
        # constructors
        mt_base() except +

        # attributes
        double awr
        int mat
        int mf
        int mt
        int nuc_id

        # methods

        pass



cdef extern from "endf_mt.h" namespace "pyne":

    cdef cppclass mtfpy_mf8(mt_base):
        # constructors
        mtfpy_mf8() except +

        # attributes
        cpp_vector[double] e
        cpp_vector[int] i
        int le
        cpp_vector[cpp_vector[cpp_vector[double]]] yields

        # methods

        pass



cdef extern from "endf_mt.h" namespace "pyne":

    cdef cppclass mt460_mf1(mt_base):
        # constructors
        mt460_mf1() except +

        # attributes
        cpp_vector[double] elist
        cpp_vector[cpp_vector[int]] intn
        cpp_vector[double] lambdas
        int lo
        cpp_vector[cpp_vector[int]] nbt
        int ng
        cpp_vector[cpp_vector[double]] t
        cpp_vector[cpp_vector[double]] tint

        # methods

        pass



cdef extern from "endf_mt.h" namespace "pyne":

    cdef cppclass mt458_mf1(mt_base):
        # constructors
        mt458_mf1() except +

        # attributes
        cpp_vector[double] deb
        cpp_vector[double] defr
        cpp_vector[double] degd
        cpp_vector[double] degp
        cpp_vector[double] dend
        cpp_vector[double] denp
        cpp_vector[double] denu
        cpp_vector[double] der
        cpp_vector[double] det
        cpp_vector[double] eb
        cpp_vector[double] efr
        cpp_vector[double] egd
        cpp_vector[double] egp
        cpp_vector[double] end
        cpp_vector[double] enp
        cpp_vector[double] enu
        cpp_vector[double] er
        cpp_vector[double] et

        # methods

        pass



cdef extern from "endf_mt.h" namespace "pyne":

    cdef cppclass mt456_mf1(mt_base):
        # constructors
        mt456_mf1() except +

        # attributes
        cpp_vector[double] eint
        cpp_vector[int] intn
        int lnu
        cpp_vector[int] nbt
        cpp_vector[double] nu
        cpp_vector[double] nu_e

        # methods

        pass



cdef extern from "endf_mt.h" namespace "pyne":

    cdef cppclass mt455_mf1(mt_base):
        # constructors
        mt455_mf1() except +

        # attributes
        cpp_vector[cpp_vector[double]] alpha_arr
        cpp_vector[double] eint
        cpp_vector[int] einti
        cpp_vector[int] intn
        cpp_vector[cpp_vector[double]] lambda_arr
        cpp_vector[double] lambdas
        int ldg
        int lnu
        cpp_vector[int] nbt
        cpp_vector[int] ne
        cpp_vector[double] nu_d

        # methods

        pass



cdef extern from "endf_mt.h" namespace "pyne":

    cdef cppclass mt452_mf1(mt_base):
        # constructors
        mt452_mf1() except +

        # attributes
        cpp_vector[double] eint
        cpp_vector[int] intn
        int lnu
        cpp_vector[int] nbt
        cpp_vector[double] nu_e
        cpp_vector[double] poly

        # methods

        pass



cdef extern from "endf_mt.h" namespace "pyne":

    cdef cppclass mt451(mt_base):
        # constructors
        mt451() except +

        # attributes
        double awi
        double elis
        double emax
        int ldrv
        int lfi
        int lis
        int liso
        int lrel
        int lrp
        cpp_vector[cpp_vector[int]] mt_list
        int nfor
        int nlib
        int nmod
        int nsub
        int nver
        int nwd
        int nxc
        int sta
        double temp

        # methods

        pass



cdef extern from "endf.h" namespace "pyne":

    cdef cppclass library:
        # constructors
        library() except +

        # attributes
        cpp_vector[cpp_vector[int]] content_list

        # methods
        cpp_vector[cpp_vector[int]] get_content_list() except +
        void read_endf() except +
        void read_endf(std_string) except +
        mt451 get_mt451 "get< mt451 >" () except +
        mt451 get_mt451 "get< mt451 >" (int) except +
        mt451 get_mt451 "get< mt451 >" (int, int) except +
        mt451 get_mt451 "get< mt451 >" (int, int, int) except +
        mt452_mf1 get_mt452_mf1 "get< mt452_mf1 >" () except +
        mt452_mf1 get_mt452_mf1 "get< mt452_mf1 >" (int) except +
        mt452_mf1 get_mt452_mf1 "get< mt452_mf1 >" (int, int) except +
        mt452_mf1 get_mt452_mf1 "get< mt452_mf1 >" (int, int, int) except +
        mt455_mf1 get_mt455_mf1 "get< mt455_mf1 >" () except +
        mt455_mf1 get_mt455_mf1 "get< mt455_mf1 >" (int) except +
        mt455_mf1 get_mt455_mf1 "get< mt455_mf1 >" (int, int) except +
        mt455_mf1 get_mt455_mf1 "get< mt455_mf1 >" (int, int, int) except +
        mt456_mf1 get_mt456_mf1 "get< mt456_mf1 >" () except +
        mt456_mf1 get_mt456_mf1 "get< mt456_mf1 >" (int) except +
        mt456_mf1 get_mt456_mf1 "get< mt456_mf1 >" (int, int) except +
        mt456_mf1 get_mt456_mf1 "get< mt456_mf1 >" (int, int, int) except +
        mt458_mf1 get_mt458_mf1 "get< mt458_mf1 >" () except +
        mt458_mf1 get_mt458_mf1 "get< mt458_mf1 >" (int) except +
        mt458_mf1 get_mt458_mf1 "get< mt458_mf1 >" (int, int) except +
        mt458_mf1 get_mt458_mf1 "get< mt458_mf1 >" (int, int, int) except +
        mt460_mf1 get_mt460_mf1 "get< mt460_mf1 >" () except +
        mt460_mf1 get_mt460_mf1 "get< mt460_mf1 >" (int) except +
        mt460_mf1 get_mt460_mf1 "get< mt460_mf1 >" (int, int) except +
        mt460_mf1 get_mt460_mf1 "get< mt460_mf1 >" (int, int, int) except +
        mtfpy_mf8 get_mtfpy_mf8 "get< mtfpy_mf8 >" () except +
        mtfpy_mf8 get_mtfpy_mf8 "get< mtfpy_mf8 >" (int) except +
        mtfpy_mf8 get_mtfpy_mf8 "get< mtfpy_mf8 >" (int, int) except +
        mtfpy_mf8 get_mtfpy_mf8 "get< mtfpy_mf8 >" (int, int, int) except +
        pass




{'cpppxd_footer': '', 'pyx_header': '', 'pxd_header': '', 'pxd_footer': '', 'cpppxd_header': '', 'pyx_footer': ''}