###################
###  WARNING!!! ###
###################
# This file has been autogenerated

# Cython imports
from cython.operator cimport dereference as deref
from cython.operator cimport preincrement as inc
from libc.stdlib cimport malloc, free
from libc.string cimport memcpy
from cpython.version cimport PY_MAJOR_VERSION
from cpython.ref cimport PyTypeObject
from cpython.type cimport PyType_Ready
from cpython.object cimport Py_LT, Py_LE, Py_EQ, Py_NE, Py_GT, Py_GE

# Python Imports
import collections

cimport numpy as np
import numpy as np
np.import_array()

cimport extra_types

# Cython imports for types
cimport numpy as np
from libcpp.vector cimport vector as cpp_vector

# imports for types
import numpy as np

dtypes = {}

if PY_MAJOR_VERSION >= 3:
    basestring = str

# Dirty ifdef, else, else preprocessor hack
# see http://comments.gmane.org/gmane.comp.python.cython.user/4080
cdef extern from *:
    cdef void emit_ifpy2k "#if PY_MAJOR_VERSION == 2 //" ()
    cdef void emit_ifpy3k "#if PY_MAJOR_VERSION == 3 //" ()
    cdef void emit_else "#else //" ()
    cdef void emit_endif "#endif //" ()

# cpp_vector[int] dtype
cdef MemoryKnight[cpp_vector[int]] mk_vector_int = MemoryKnight[cpp_vector[int]]()
cdef MemoryKnight[PyXDVectorInt_Type] mk_vector_int_type = MemoryKnight[PyXDVectorInt_Type]()

cdef object pyxd_vector_int_getitem(void * data, void * arr):
    cdef np.ndarray data_proxy
    cdef np.npy_intp data_proxy_shape[1]
    data_proxy_shape[0] = <np.npy_intp> (<cpp_vector[int] *> data)[0].size()
    data_proxy = np.PyArray_SimpleNewFromData(1, data_proxy_shape, np.NPY_INT32, &(<cpp_vector[int] *> data)[0][0])
    pyval = data_proxy
    return pyval

cdef int pyxd_vector_int_setitem(object value, void * data, void * arr):
    cdef cpp_vector[int] * new_data
    cdef cpp_vector[int] value_proxy
    cdef int ivalue
    cdef int value_size
    cdef int * value_data
    if isinstance(value, list) or isinstance(value, tuple) or isinstance(value, np.ndarray):
        # value is a ('vector', 'int32', 0)
        value_size = len(value)
        if isinstance(value, np.ndarray) and (<np.ndarray> value).descr.type_num == xd_vector_int.num:
            value_data = <int *> np.PyArray_DATA(<np.ndarray> value)
            value_proxy = cpp_vector[int](<size_t> value_size)
            for ivalue in range(value_size):
                value_proxy[ivalue] = value_data[ivalue]
        else:
            value_proxy = cpp_vector[int](<size_t> value_size)
            for ivalue in range(value_size):
                value_proxy[ivalue] = <int> value[ivalue]
        new_data = mk_vector_int.renew(data)
        new_data[0] = value_proxy
        return 0
    else:
        return -1

cdef void pyxd_vector_int_copyswapn(void * dest, np.npy_intp dstride, void * src, np.npy_intp sstride, np.npy_intp n, int swap, void * arr):
    cdef np.npy_intp i
    cdef char * a 
    cdef char * b 
    cdef char c = 0
    cdef int j
    cdef int m
    cdef cpp_vector[int] * new_dest

    if src != NULL:
        if (sstride == sizeof(cpp_vector[int]) and dstride == sizeof(cpp_vector[int])):
            new_dest = mk_vector_int.renew(dest)
            new_dest[0] = deref(<cpp_vector[int] *> src)
        else:
            a = <char *> dest
            b = <char *> src
            for i in range(n):
                new_dest = mk_vector_int.renew(<void *> a)
                new_dest[0] = deref(<cpp_vector[int] *> b)
                a += dstride
                b += sstride
    if swap: 
        m = sizeof(cpp_vector[int]) / 2
        a = <char *> dest
        for i in range(n, 0, -1):
            b = a + (sizeof(cpp_vector[int]) - 1);
            for j in range(m):
                c = a[0]
                a[0] = b[0]
                a += 1
                b[0] = c
                b -= 1
            a += dstride - m

cdef void pyxd_vector_int_copyswap(void * dest, void * src, int swap, void * arr):
    cdef char * a 
    cdef char * b 
    cdef char c = 0
    cdef int j
    cdef int m
    cdef cpp_vector[int] * new_dest
    if src != NULL:
        new_dest = mk_vector_int.renew(dest)
        new_dest[0] = (<cpp_vector[int] *> src)[0]
    if swap:
        m = sizeof(cpp_vector[int]) / 2
        a = <char *> dest
        b = a + (sizeof(cpp_vector[int]) - 1);
        for j in range(m):
            c = a[0]
            a[0] = b[0]
            a += 1
            b[0] = c
            b -= 1

cdef np.npy_bool pyxd_vector_int_nonzero(void * data, void * arr):
    return (data != NULL)
    # FIXME comparisons not defined for arbitrary types
    #cdef cpp_vector[int] zero = cpp_vector[int]()
    #return ((<cpp_vector[int] *> data)[0] != zero)

cdef int pyxd_vector_int_compare(const void * d1, const void * d2, void * arr):
    return (d1 == d2) - 1
    # FIXME comparisons not defined for arbitrary types
    #if deref(<cpp_vector[int] *> d1) == deref(<cpp_vector[int] *> d2):
    #    return 0
    #else:
    #    return -1

cdef PyArray_ArrFuncs PyXD_VectorInt_ArrFuncs 
PyArray_InitArrFuncs(&PyXD_VectorInt_ArrFuncs)
PyXD_VectorInt_ArrFuncs.getitem = <PyArray_GetItemFunc *> (&pyxd_vector_int_getitem)
PyXD_VectorInt_ArrFuncs.setitem = <PyArray_SetItemFunc *> (&pyxd_vector_int_setitem)
PyXD_VectorInt_ArrFuncs.copyswapn = <PyArray_CopySwapNFunc *> (&pyxd_vector_int_copyswapn)
PyXD_VectorInt_ArrFuncs.copyswap = <PyArray_CopySwapFunc *> (&pyxd_vector_int_copyswap)
PyXD_VectorInt_ArrFuncs.nonzero = <PyArray_NonzeroFunc *> (&pyxd_vector_int_nonzero)
PyXD_VectorInt_ArrFuncs.compare = <PyArray_CompareFunc *> (&pyxd_vector_int_compare)

cdef object pyxd_vector_int_type_alloc(PyTypeObject * self, Py_ssize_t nitems):
    cdef PyXDVectorInt_Type * cval
    cdef object pyval
    cval = mk_vector_int_type.defnew()
    cval.ob_typ = self
    pyval = <object> cval
    return pyval

cdef void pyxd_vector_int_type_dealloc(object self):
    cdef PyXDVectorInt_Type * cself = <PyXDVectorInt_Type *> self
    mk_vector_int_type.deall(cself)
    return

cdef object pyxd_vector_int_type_new(PyTypeObject * subtype, object args, object kwds):
    return pyxd_vector_int_type_alloc(subtype, 0)

cdef void pyxd_vector_int_type_free(void * self):
    return

cdef object pyxd_vector_int_type_str(object self):
    cdef PyXDVectorInt_Type * cself = <PyXDVectorInt_Type *> self
    cdef np.ndarray val_proxy
    cdef np.npy_intp val_proxy_shape[1]
    val_proxy_shape[0] = <np.npy_intp> (cself.obval).size()
    val_proxy = np.PyArray_SimpleNewFromData(1, val_proxy_shape, np.NPY_INT32, &(cself.obval)[0])
    pyval = val_proxy
    s = str(pyval)
    return s

cdef object pyxd_vector_int_type_repr(object self):
    cdef PyXDVectorInt_Type * cself = <PyXDVectorInt_Type *> self
    cdef np.ndarray val_proxy
    cdef np.npy_intp val_proxy_shape[1]
    val_proxy_shape[0] = <np.npy_intp> (cself.obval).size()
    val_proxy = np.PyArray_SimpleNewFromData(1, val_proxy_shape, np.NPY_INT32, &(cself.obval)[0])
    pyval = val_proxy
    s = repr(pyval)
    return s

cdef int pyxd_vector_int_type_compare(object a, object b):
    return (a is b) - 1
    # FIXME comparisons not defined for arbitrary types
    #cdef PyXDVectorInt_Type * x
    #cdef PyXDVectorInt_Type * y
    #if type(a) is not type(b):
    #    raise NotImplementedError
    #x = <PyXDVectorInt_Type *> a
    #y = <PyXDVectorInt_Type *> b
    #if (x.obval == y.obval):
    #    return 0
    #elif (x.obval < y.obval):
    #    return -1
    #elif (x.obval > y.obval):
    #    return 1
    #else:
    #    raise NotImplementedError

cdef object pyxd_vector_int_type_richcompare(object a, object b, int op):
    if op == Py_EQ:
        return (a is b)
    elif op == Py_NE:
        return (a is not b)
    else:
        return NotImplemented
    # FIXME comparisons not defined for arbitrary types
    #cdef PyXDVectorInt_Type * x
    #cdef PyXDVectorInt_Type * y
    #if type(a) is not type(b):
    #    return NotImplemented
    #x = <PyXDVectorInt_Type *> a
    #y = <PyXDVectorInt_Type *> b
    #if op == Py_LT:
    #    return (x.obval < y.obval)
    #elif op == Py_LE:
    #    return (x.obval <= y.obval)
    #elif op == Py_EQ:
    #    return (x.obval == y.obval)
    #elif op == Py_NE:
    #    return (x.obval != y.obval)
    #elif op == Py_GT:
    #    return (x.obval > y.obval)
    #elif op == Py_GE:
    #    return (x.obval >= y.obval)
    #else:
    #    return NotImplemented    

cdef long pyxd_vector_int_type_hash(object self):
    return id(self)

cdef PyMemberDef pyxd_vector_int_type_members[1]
pyxd_vector_int_type_members[0] = PyMemberDef(NULL, 0, 0, 0, NULL)

cdef PyGetSetDef pyxd_vector_int_type_getset[1]
pyxd_vector_int_type_getset[0] = PyGetSetDef(NULL)

cdef bint pyxd_vector_int_is_ready
cdef type PyXD_VectorInt = type("xd_vector_int", ((<object> PyArray_API[10]),), {})
pyxd_vector_int_is_ready = PyType_Ready(<object> PyXD_VectorInt)
(<PyTypeObject *> PyXD_VectorInt).tp_basicsize = sizeof(PyXDVectorInt_Type)
(<PyTypeObject *> PyXD_VectorInt).tp_itemsize = 0
(<PyTypeObject *> PyXD_VectorInt).tp_doc = "Python scalar type for cpp_vector[int]"
(<PyTypeObject *> PyXD_VectorInt).tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE | Py_TPFLAGS_CHECKTYPES | Py_TPFLAGS_HEAPTYPE
(<PyTypeObject *> PyXD_VectorInt).tp_alloc = pyxd_vector_int_type_alloc
(<PyTypeObject *> PyXD_VectorInt).tp_dealloc = pyxd_vector_int_type_dealloc
(<PyTypeObject *> PyXD_VectorInt).tp_new = pyxd_vector_int_type_new
(<PyTypeObject *> PyXD_VectorInt).tp_free = pyxd_vector_int_type_free
(<PyTypeObject *> PyXD_VectorInt).tp_str = pyxd_vector_int_type_str
(<PyTypeObject *> PyXD_VectorInt).tp_repr = pyxd_vector_int_type_repr
(<PyTypeObject *> PyXD_VectorInt).tp_base = (<PyTypeObject *> PyArray_API[10])  # PyGenericArrType_Type
(<PyTypeObject *> PyXD_VectorInt).tp_hash = pyxd_vector_int_type_hash
emit_ifpy2k()
(<PyTypeObject *> PyXD_VectorInt).tp_compare = &pyxd_vector_int_type_compare
emit_endif()
(<PyTypeObject *> PyXD_VectorInt).tp_richcompare = pyxd_vector_int_type_richcompare
(<PyTypeObject *> PyXD_VectorInt).tp_members = pyxd_vector_int_type_members
(<PyTypeObject *> PyXD_VectorInt).tp_getset = pyxd_vector_int_type_getset
pyxd_vector_int_is_ready = PyType_Ready(<object> PyXD_VectorInt)
Py_INCREF(PyXD_VectorInt)
XDVectorInt = PyXD_VectorInt

cdef PyArray_Descr * c_xd_vector_int_descr = <PyArray_Descr *> malloc(sizeof(PyArray_Descr))
(<PyObject *> c_xd_vector_int_descr).ob_refcnt = 0 # ob_refcnt
(<PyObject *> c_xd_vector_int_descr).ob_type = <PyTypeObject *> PyArray_API[3]
c_xd_vector_int_descr.typeobj = <PyTypeObject *> PyXD_VectorInt # typeobj
c_xd_vector_int_descr.kind = 'x'  # kind, for xdress
c_xd_vector_int_descr.type = 'x'  # type
c_xd_vector_int_descr.byteorder = '='  # byteorder
c_xd_vector_int_descr.flags = 0    # flags
c_xd_vector_int_descr.type_num = 0    # type_num, assigned at registration
c_xd_vector_int_descr.elsize = sizeof(cpp_vector[int])  # elsize, 
c_xd_vector_int_descr.alignment = 8  # alignment
c_xd_vector_int_descr.subarray = NULL  # subarray
c_xd_vector_int_descr.fields = NULL  # fields
c_xd_vector_int_descr.names = NULL
(<PyArray_Descr *> c_xd_vector_int_descr).f = <PyArray_ArrFuncs *> &PyXD_VectorInt_ArrFuncs  # f == PyArray_ArrFuncs

cdef object xd_vector_int_descr = <object> (<void *> c_xd_vector_int_descr)
Py_INCREF(<object> xd_vector_int_descr)
xd_vector_int = xd_vector_int_descr
cdef int xd_vector_int_num = PyArray_RegisterDataType(c_xd_vector_int_descr)
dtypes['vector_int'] = xd_vector_int
dtypes['xd_vector_int'] = xd_vector_int
dtypes[xd_vector_int_num] = xd_vector_int



# cpp_vector[double] dtype
cdef MemoryKnight[cpp_vector[double]] mk_vector_double = MemoryKnight[cpp_vector[double]]()
cdef MemoryKnight[PyXDVectorDouble_Type] mk_vector_double_type = MemoryKnight[PyXDVectorDouble_Type]()

cdef object pyxd_vector_double_getitem(void * data, void * arr):
    cdef np.ndarray data_proxy
    cdef np.npy_intp data_proxy_shape[1]
    data_proxy_shape[0] = <np.npy_intp> (<cpp_vector[double] *> data)[0].size()
    data_proxy = np.PyArray_SimpleNewFromData(1, data_proxy_shape, np.NPY_FLOAT64, &(<cpp_vector[double] *> data)[0][0])
    pyval = data_proxy
    return pyval

cdef int pyxd_vector_double_setitem(object value, void * data, void * arr):
    cdef cpp_vector[double] * new_data
    cdef cpp_vector[double] value_proxy
    cdef int ivalue
    cdef int value_size
    cdef double * value_data
    if isinstance(value, list) or isinstance(value, tuple) or isinstance(value, np.ndarray):
        # value is a ('vector', 'float64', 0)
        value_size = len(value)
        if isinstance(value, np.ndarray) and (<np.ndarray> value).descr.type_num == xd_vector_double.num:
            value_data = <double *> np.PyArray_DATA(<np.ndarray> value)
            value_proxy = cpp_vector[double](<size_t> value_size)
            for ivalue in range(value_size):
                value_proxy[ivalue] = value_data[ivalue]
        else:
            value_proxy = cpp_vector[double](<size_t> value_size)
            for ivalue in range(value_size):
                value_proxy[ivalue] = <double> value[ivalue]
        new_data = mk_vector_double.renew(data)
        new_data[0] = value_proxy
        return 0
    else:
        return -1

cdef void pyxd_vector_double_copyswapn(void * dest, np.npy_intp dstride, void * src, np.npy_intp sstride, np.npy_intp n, int swap, void * arr):
    cdef np.npy_intp i
    cdef char * a 
    cdef char * b 
    cdef char c = 0
    cdef int j
    cdef int m
    cdef cpp_vector[double] * new_dest

    if src != NULL:
        if (sstride == sizeof(cpp_vector[double]) and dstride == sizeof(cpp_vector[double])):
            new_dest = mk_vector_double.renew(dest)
            new_dest[0] = deref(<cpp_vector[double] *> src)
        else:
            a = <char *> dest
            b = <char *> src
            for i in range(n):
                new_dest = mk_vector_double.renew(<void *> a)
                new_dest[0] = deref(<cpp_vector[double] *> b)
                a += dstride
                b += sstride
    if swap: 
        m = sizeof(cpp_vector[double]) / 2
        a = <char *> dest
        for i in range(n, 0, -1):
            b = a + (sizeof(cpp_vector[double]) - 1);
            for j in range(m):
                c = a[0]
                a[0] = b[0]
                a += 1
                b[0] = c
                b -= 1
            a += dstride - m

cdef void pyxd_vector_double_copyswap(void * dest, void * src, int swap, void * arr):
    cdef char * a 
    cdef char * b 
    cdef char c = 0
    cdef int j
    cdef int m
    cdef cpp_vector[double] * new_dest
    if src != NULL:
        new_dest = mk_vector_double.renew(dest)
        new_dest[0] = (<cpp_vector[double] *> src)[0]
    if swap:
        m = sizeof(cpp_vector[double]) / 2
        a = <char *> dest
        b = a + (sizeof(cpp_vector[double]) - 1);
        for j in range(m):
            c = a[0]
            a[0] = b[0]
            a += 1
            b[0] = c
            b -= 1

cdef np.npy_bool pyxd_vector_double_nonzero(void * data, void * arr):
    return (data != NULL)
    # FIXME comparisons not defined for arbitrary types
    #cdef cpp_vector[double] zero = cpp_vector[double]()
    #return ((<cpp_vector[double] *> data)[0] != zero)

cdef int pyxd_vector_double_compare(const void * d1, const void * d2, void * arr):
    return (d1 == d2) - 1
    # FIXME comparisons not defined for arbitrary types
    #if deref(<cpp_vector[double] *> d1) == deref(<cpp_vector[double] *> d2):
    #    return 0
    #else:
    #    return -1

cdef PyArray_ArrFuncs PyXD_VectorDouble_ArrFuncs 
PyArray_InitArrFuncs(&PyXD_VectorDouble_ArrFuncs)
PyXD_VectorDouble_ArrFuncs.getitem = <PyArray_GetItemFunc *> (&pyxd_vector_double_getitem)
PyXD_VectorDouble_ArrFuncs.setitem = <PyArray_SetItemFunc *> (&pyxd_vector_double_setitem)
PyXD_VectorDouble_ArrFuncs.copyswapn = <PyArray_CopySwapNFunc *> (&pyxd_vector_double_copyswapn)
PyXD_VectorDouble_ArrFuncs.copyswap = <PyArray_CopySwapFunc *> (&pyxd_vector_double_copyswap)
PyXD_VectorDouble_ArrFuncs.nonzero = <PyArray_NonzeroFunc *> (&pyxd_vector_double_nonzero)
PyXD_VectorDouble_ArrFuncs.compare = <PyArray_CompareFunc *> (&pyxd_vector_double_compare)

cdef object pyxd_vector_double_type_alloc(PyTypeObject * self, Py_ssize_t nitems):
    cdef PyXDVectorDouble_Type * cval
    cdef object pyval
    cval = mk_vector_double_type.defnew()
    cval.ob_typ = self
    pyval = <object> cval
    return pyval

cdef void pyxd_vector_double_type_dealloc(object self):
    cdef PyXDVectorDouble_Type * cself = <PyXDVectorDouble_Type *> self
    mk_vector_double_type.deall(cself)
    return

cdef object pyxd_vector_double_type_new(PyTypeObject * subtype, object args, object kwds):
    return pyxd_vector_double_type_alloc(subtype, 0)

cdef void pyxd_vector_double_type_free(void * self):
    return

cdef object pyxd_vector_double_type_str(object self):
    cdef PyXDVectorDouble_Type * cself = <PyXDVectorDouble_Type *> self
    cdef np.ndarray val_proxy
    cdef np.npy_intp val_proxy_shape[1]
    val_proxy_shape[0] = <np.npy_intp> (cself.obval).size()
    val_proxy = np.PyArray_SimpleNewFromData(1, val_proxy_shape, np.NPY_FLOAT64, &(cself.obval)[0])
    pyval = val_proxy
    s = str(pyval)
    return s

cdef object pyxd_vector_double_type_repr(object self):
    cdef PyXDVectorDouble_Type * cself = <PyXDVectorDouble_Type *> self
    cdef np.ndarray val_proxy
    cdef np.npy_intp val_proxy_shape[1]
    val_proxy_shape[0] = <np.npy_intp> (cself.obval).size()
    val_proxy = np.PyArray_SimpleNewFromData(1, val_proxy_shape, np.NPY_FLOAT64, &(cself.obval)[0])
    pyval = val_proxy
    s = repr(pyval)
    return s

cdef int pyxd_vector_double_type_compare(object a, object b):
    return (a is b) - 1
    # FIXME comparisons not defined for arbitrary types
    #cdef PyXDVectorDouble_Type * x
    #cdef PyXDVectorDouble_Type * y
    #if type(a) is not type(b):
    #    raise NotImplementedError
    #x = <PyXDVectorDouble_Type *> a
    #y = <PyXDVectorDouble_Type *> b
    #if (x.obval == y.obval):
    #    return 0
    #elif (x.obval < y.obval):
    #    return -1
    #elif (x.obval > y.obval):
    #    return 1
    #else:
    #    raise NotImplementedError

cdef object pyxd_vector_double_type_richcompare(object a, object b, int op):
    if op == Py_EQ:
        return (a is b)
    elif op == Py_NE:
        return (a is not b)
    else:
        return NotImplemented
    # FIXME comparisons not defined for arbitrary types
    #cdef PyXDVectorDouble_Type * x
    #cdef PyXDVectorDouble_Type * y
    #if type(a) is not type(b):
    #    return NotImplemented
    #x = <PyXDVectorDouble_Type *> a
    #y = <PyXDVectorDouble_Type *> b
    #if op == Py_LT:
    #    return (x.obval < y.obval)
    #elif op == Py_LE:
    #    return (x.obval <= y.obval)
    #elif op == Py_EQ:
    #    return (x.obval == y.obval)
    #elif op == Py_NE:
    #    return (x.obval != y.obval)
    #elif op == Py_GT:
    #    return (x.obval > y.obval)
    #elif op == Py_GE:
    #    return (x.obval >= y.obval)
    #else:
    #    return NotImplemented    

cdef long pyxd_vector_double_type_hash(object self):
    return id(self)

cdef PyMemberDef pyxd_vector_double_type_members[1]
pyxd_vector_double_type_members[0] = PyMemberDef(NULL, 0, 0, 0, NULL)

cdef PyGetSetDef pyxd_vector_double_type_getset[1]
pyxd_vector_double_type_getset[0] = PyGetSetDef(NULL)

cdef bint pyxd_vector_double_is_ready
cdef type PyXD_VectorDouble = type("xd_vector_double", ((<object> PyArray_API[10]),), {})
pyxd_vector_double_is_ready = PyType_Ready(<object> PyXD_VectorDouble)
(<PyTypeObject *> PyXD_VectorDouble).tp_basicsize = sizeof(PyXDVectorDouble_Type)
(<PyTypeObject *> PyXD_VectorDouble).tp_itemsize = 0
(<PyTypeObject *> PyXD_VectorDouble).tp_doc = "Python scalar type for cpp_vector[double]"
(<PyTypeObject *> PyXD_VectorDouble).tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE | Py_TPFLAGS_CHECKTYPES | Py_TPFLAGS_HEAPTYPE
(<PyTypeObject *> PyXD_VectorDouble).tp_alloc = pyxd_vector_double_type_alloc
(<PyTypeObject *> PyXD_VectorDouble).tp_dealloc = pyxd_vector_double_type_dealloc
(<PyTypeObject *> PyXD_VectorDouble).tp_new = pyxd_vector_double_type_new
(<PyTypeObject *> PyXD_VectorDouble).tp_free = pyxd_vector_double_type_free
(<PyTypeObject *> PyXD_VectorDouble).tp_str = pyxd_vector_double_type_str
(<PyTypeObject *> PyXD_VectorDouble).tp_repr = pyxd_vector_double_type_repr
(<PyTypeObject *> PyXD_VectorDouble).tp_base = (<PyTypeObject *> PyArray_API[10])  # PyGenericArrType_Type
(<PyTypeObject *> PyXD_VectorDouble).tp_hash = pyxd_vector_double_type_hash
emit_ifpy2k()
(<PyTypeObject *> PyXD_VectorDouble).tp_compare = &pyxd_vector_double_type_compare
emit_endif()
(<PyTypeObject *> PyXD_VectorDouble).tp_richcompare = pyxd_vector_double_type_richcompare
(<PyTypeObject *> PyXD_VectorDouble).tp_members = pyxd_vector_double_type_members
(<PyTypeObject *> PyXD_VectorDouble).tp_getset = pyxd_vector_double_type_getset
pyxd_vector_double_is_ready = PyType_Ready(<object> PyXD_VectorDouble)
Py_INCREF(PyXD_VectorDouble)
XDVectorDouble = PyXD_VectorDouble

cdef PyArray_Descr * c_xd_vector_double_descr = <PyArray_Descr *> malloc(sizeof(PyArray_Descr))
(<PyObject *> c_xd_vector_double_descr).ob_refcnt = 0 # ob_refcnt
(<PyObject *> c_xd_vector_double_descr).ob_type = <PyTypeObject *> PyArray_API[3]
c_xd_vector_double_descr.typeobj = <PyTypeObject *> PyXD_VectorDouble # typeobj
c_xd_vector_double_descr.kind = 'x'  # kind, for xdress
c_xd_vector_double_descr.type = 'x'  # type
c_xd_vector_double_descr.byteorder = '='  # byteorder
c_xd_vector_double_descr.flags = 0    # flags
c_xd_vector_double_descr.type_num = 0    # type_num, assigned at registration
c_xd_vector_double_descr.elsize = sizeof(cpp_vector[double])  # elsize, 
c_xd_vector_double_descr.alignment = 8  # alignment
c_xd_vector_double_descr.subarray = NULL  # subarray
c_xd_vector_double_descr.fields = NULL  # fields
c_xd_vector_double_descr.names = NULL
(<PyArray_Descr *> c_xd_vector_double_descr).f = <PyArray_ArrFuncs *> &PyXD_VectorDouble_ArrFuncs  # f == PyArray_ArrFuncs

cdef object xd_vector_double_descr = <object> (<void *> c_xd_vector_double_descr)
Py_INCREF(<object> xd_vector_double_descr)
xd_vector_double = xd_vector_double_descr
cdef int xd_vector_double_num = PyArray_RegisterDataType(c_xd_vector_double_descr)
dtypes['vector_double'] = xd_vector_double
dtypes['xd_vector_double'] = xd_vector_double
dtypes[xd_vector_double_num] = xd_vector_double



# cpp_vector[cpp_vector[double]] dtype
cdef MemoryKnight[cpp_vector[cpp_vector[double]]] mk_vector_vector_double = MemoryKnight[cpp_vector[cpp_vector[double]]]()
cdef MemoryKnight[PyXDVectorVectorDouble_Type] mk_vector_vector_double_type = MemoryKnight[PyXDVectorVectorDouble_Type]()

cdef object pyxd_vector_vector_double_getitem(void * data, void * arr):
    cdef np.ndarray data_proxy
    cdef np.npy_intp data_proxy_shape[1]
    data_proxy_shape[0] = <np.npy_intp> (<cpp_vector[cpp_vector[double]] *> data)[0].size()
    data_proxy = np.PyArray_SimpleNewFromData(1, data_proxy_shape, xd_vector_double.num, &(<cpp_vector[cpp_vector[double]] *> data)[0][0])
    pyval = data_proxy
    return pyval

cdef int pyxd_vector_vector_double_setitem(object value, void * data, void * arr):
    cdef cpp_vector[cpp_vector[double]] * new_data
    cdef cpp_vector[cpp_vector[double]] value_proxy
    cdef int ivalue
    cdef int value_size
    cdef cpp_vector[double] * value_data
    if isinstance(value, list) or isinstance(value, tuple) or isinstance(value, np.ndarray):
        # value is a ('vector', ('vector', 'float64', 0), 0)
        value_size = len(value)
        if isinstance(value, np.ndarray) and (<np.ndarray> value).descr.type_num == xd_vector_vector_double.num:
            value_data = <cpp_vector[double] *> np.PyArray_DATA(<np.ndarray> value)
            value_proxy = cpp_vector[cpp_vector[double]](<size_t> value_size)
            for ivalue in range(value_size):
                value_proxy[ivalue] = value_data[ivalue]
        else:
            value_proxy = cpp_vector[cpp_vector[double]](<size_t> value_size)
            for ivalue in range(value_size):
                value_proxy[ivalue] = <cpp_vector[double]> value[ivalue]
        new_data = mk_vector_vector_double.renew(data)
        new_data[0] = value_proxy
        return 0
    else:
        return -1

cdef void pyxd_vector_vector_double_copyswapn(void * dest, np.npy_intp dstride, void * src, np.npy_intp sstride, np.npy_intp n, int swap, void * arr):
    cdef np.npy_intp i
    cdef char * a 
    cdef char * b 
    cdef char c = 0
    cdef int j
    cdef int m
    cdef cpp_vector[cpp_vector[double]] * new_dest

    if src != NULL:
        if (sstride == sizeof(cpp_vector[cpp_vector[double]]) and dstride == sizeof(cpp_vector[cpp_vector[double]])):
            new_dest = mk_vector_vector_double.renew(dest)
            new_dest[0] = deref(<cpp_vector[cpp_vector[double]] *> src)
        else:
            a = <char *> dest
            b = <char *> src
            for i in range(n):
                new_dest = mk_vector_vector_double.renew(<void *> a)
                new_dest[0] = deref(<cpp_vector[cpp_vector[double]] *> b)
                a += dstride
                b += sstride
    if swap: 
        m = sizeof(cpp_vector[cpp_vector[double]]) / 2
        a = <char *> dest
        for i in range(n, 0, -1):
            b = a + (sizeof(cpp_vector[cpp_vector[double]]) - 1);
            for j in range(m):
                c = a[0]
                a[0] = b[0]
                a += 1
                b[0] = c
                b -= 1
            a += dstride - m

cdef void pyxd_vector_vector_double_copyswap(void * dest, void * src, int swap, void * arr):
    cdef char * a 
    cdef char * b 
    cdef char c = 0
    cdef int j
    cdef int m
    cdef cpp_vector[cpp_vector[double]] * new_dest
    if src != NULL:
        new_dest = mk_vector_vector_double.renew(dest)
        new_dest[0] = (<cpp_vector[cpp_vector[double]] *> src)[0]
    if swap:
        m = sizeof(cpp_vector[cpp_vector[double]]) / 2
        a = <char *> dest
        b = a + (sizeof(cpp_vector[cpp_vector[double]]) - 1);
        for j in range(m):
            c = a[0]
            a[0] = b[0]
            a += 1
            b[0] = c
            b -= 1

cdef np.npy_bool pyxd_vector_vector_double_nonzero(void * data, void * arr):
    return (data != NULL)
    # FIXME comparisons not defined for arbitrary types
    #cdef cpp_vector[cpp_vector[double]] zero = cpp_vector[cpp_vector[double]]()
    #return ((<cpp_vector[cpp_vector[double]] *> data)[0] != zero)

cdef int pyxd_vector_vector_double_compare(const void * d1, const void * d2, void * arr):
    return (d1 == d2) - 1
    # FIXME comparisons not defined for arbitrary types
    #if deref(<cpp_vector[cpp_vector[double]] *> d1) == deref(<cpp_vector[cpp_vector[double]] *> d2):
    #    return 0
    #else:
    #    return -1

cdef PyArray_ArrFuncs PyXD_VectorVectorDouble_ArrFuncs 
PyArray_InitArrFuncs(&PyXD_VectorVectorDouble_ArrFuncs)
PyXD_VectorVectorDouble_ArrFuncs.getitem = <PyArray_GetItemFunc *> (&pyxd_vector_vector_double_getitem)
PyXD_VectorVectorDouble_ArrFuncs.setitem = <PyArray_SetItemFunc *> (&pyxd_vector_vector_double_setitem)
PyXD_VectorVectorDouble_ArrFuncs.copyswapn = <PyArray_CopySwapNFunc *> (&pyxd_vector_vector_double_copyswapn)
PyXD_VectorVectorDouble_ArrFuncs.copyswap = <PyArray_CopySwapFunc *> (&pyxd_vector_vector_double_copyswap)
PyXD_VectorVectorDouble_ArrFuncs.nonzero = <PyArray_NonzeroFunc *> (&pyxd_vector_vector_double_nonzero)
PyXD_VectorVectorDouble_ArrFuncs.compare = <PyArray_CompareFunc *> (&pyxd_vector_vector_double_compare)

cdef object pyxd_vector_vector_double_type_alloc(PyTypeObject * self, Py_ssize_t nitems):
    cdef PyXDVectorVectorDouble_Type * cval
    cdef object pyval
    cval = mk_vector_vector_double_type.defnew()
    cval.ob_typ = self
    pyval = <object> cval
    return pyval

cdef void pyxd_vector_vector_double_type_dealloc(object self):
    cdef PyXDVectorVectorDouble_Type * cself = <PyXDVectorVectorDouble_Type *> self
    mk_vector_vector_double_type.deall(cself)
    return

cdef object pyxd_vector_vector_double_type_new(PyTypeObject * subtype, object args, object kwds):
    return pyxd_vector_vector_double_type_alloc(subtype, 0)

cdef void pyxd_vector_vector_double_type_free(void * self):
    return

cdef object pyxd_vector_vector_double_type_str(object self):
    cdef PyXDVectorVectorDouble_Type * cself = <PyXDVectorVectorDouble_Type *> self
    cdef np.ndarray val_proxy
    cdef np.npy_intp val_proxy_shape[1]
    val_proxy_shape[0] = <np.npy_intp> (cself.obval).size()
    val_proxy = np.PyArray_SimpleNewFromData(1, val_proxy_shape, xd_vector_double.num, &(cself.obval)[0])
    pyval = val_proxy
    s = str(pyval)
    return s

cdef object pyxd_vector_vector_double_type_repr(object self):
    cdef PyXDVectorVectorDouble_Type * cself = <PyXDVectorVectorDouble_Type *> self
    cdef np.ndarray val_proxy
    cdef np.npy_intp val_proxy_shape[1]
    val_proxy_shape[0] = <np.npy_intp> (cself.obval).size()
    val_proxy = np.PyArray_SimpleNewFromData(1, val_proxy_shape, xd_vector_double.num, &(cself.obval)[0])
    pyval = val_proxy
    s = repr(pyval)
    return s

cdef int pyxd_vector_vector_double_type_compare(object a, object b):
    return (a is b) - 1
    # FIXME comparisons not defined for arbitrary types
    #cdef PyXDVectorVectorDouble_Type * x
    #cdef PyXDVectorVectorDouble_Type * y
    #if type(a) is not type(b):
    #    raise NotImplementedError
    #x = <PyXDVectorVectorDouble_Type *> a
    #y = <PyXDVectorVectorDouble_Type *> b
    #if (x.obval == y.obval):
    #    return 0
    #elif (x.obval < y.obval):
    #    return -1
    #elif (x.obval > y.obval):
    #    return 1
    #else:
    #    raise NotImplementedError

cdef object pyxd_vector_vector_double_type_richcompare(object a, object b, int op):
    if op == Py_EQ:
        return (a is b)
    elif op == Py_NE:
        return (a is not b)
    else:
        return NotImplemented
    # FIXME comparisons not defined for arbitrary types
    #cdef PyXDVectorVectorDouble_Type * x
    #cdef PyXDVectorVectorDouble_Type * y
    #if type(a) is not type(b):
    #    return NotImplemented
    #x = <PyXDVectorVectorDouble_Type *> a
    #y = <PyXDVectorVectorDouble_Type *> b
    #if op == Py_LT:
    #    return (x.obval < y.obval)
    #elif op == Py_LE:
    #    return (x.obval <= y.obval)
    #elif op == Py_EQ:
    #    return (x.obval == y.obval)
    #elif op == Py_NE:
    #    return (x.obval != y.obval)
    #elif op == Py_GT:
    #    return (x.obval > y.obval)
    #elif op == Py_GE:
    #    return (x.obval >= y.obval)
    #else:
    #    return NotImplemented    

cdef long pyxd_vector_vector_double_type_hash(object self):
    return id(self)

cdef PyMemberDef pyxd_vector_vector_double_type_members[1]
pyxd_vector_vector_double_type_members[0] = PyMemberDef(NULL, 0, 0, 0, NULL)

cdef PyGetSetDef pyxd_vector_vector_double_type_getset[1]
pyxd_vector_vector_double_type_getset[0] = PyGetSetDef(NULL)

cdef bint pyxd_vector_vector_double_is_ready
cdef type PyXD_VectorVectorDouble = type("xd_vector_vector_double", ((<object> PyArray_API[10]),), {})
pyxd_vector_vector_double_is_ready = PyType_Ready(<object> PyXD_VectorVectorDouble)
(<PyTypeObject *> PyXD_VectorVectorDouble).tp_basicsize = sizeof(PyXDVectorVectorDouble_Type)
(<PyTypeObject *> PyXD_VectorVectorDouble).tp_itemsize = 0
(<PyTypeObject *> PyXD_VectorVectorDouble).tp_doc = "Python scalar type for cpp_vector[cpp_vector[double]]"
(<PyTypeObject *> PyXD_VectorVectorDouble).tp_flags = Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE | Py_TPFLAGS_CHECKTYPES | Py_TPFLAGS_HEAPTYPE
(<PyTypeObject *> PyXD_VectorVectorDouble).tp_alloc = pyxd_vector_vector_double_type_alloc
(<PyTypeObject *> PyXD_VectorVectorDouble).tp_dealloc = pyxd_vector_vector_double_type_dealloc
(<PyTypeObject *> PyXD_VectorVectorDouble).tp_new = pyxd_vector_vector_double_type_new
(<PyTypeObject *> PyXD_VectorVectorDouble).tp_free = pyxd_vector_vector_double_type_free
(<PyTypeObject *> PyXD_VectorVectorDouble).tp_str = pyxd_vector_vector_double_type_str
(<PyTypeObject *> PyXD_VectorVectorDouble).tp_repr = pyxd_vector_vector_double_type_repr
(<PyTypeObject *> PyXD_VectorVectorDouble).tp_base = (<PyTypeObject *> PyArray_API[10])  # PyGenericArrType_Type
(<PyTypeObject *> PyXD_VectorVectorDouble).tp_hash = pyxd_vector_vector_double_type_hash
emit_ifpy2k()
(<PyTypeObject *> PyXD_VectorVectorDouble).tp_compare = &pyxd_vector_vector_double_type_compare
emit_endif()
(<PyTypeObject *> PyXD_VectorVectorDouble).tp_richcompare = pyxd_vector_vector_double_type_richcompare
(<PyTypeObject *> PyXD_VectorVectorDouble).tp_members = pyxd_vector_vector_double_type_members
(<PyTypeObject *> PyXD_VectorVectorDouble).tp_getset = pyxd_vector_vector_double_type_getset
pyxd_vector_vector_double_is_ready = PyType_Ready(<object> PyXD_VectorVectorDouble)
Py_INCREF(PyXD_VectorVectorDouble)
XDVectorVectorDouble = PyXD_VectorVectorDouble

cdef PyArray_Descr * c_xd_vector_vector_double_descr = <PyArray_Descr *> malloc(sizeof(PyArray_Descr))
(<PyObject *> c_xd_vector_vector_double_descr).ob_refcnt = 0 # ob_refcnt
(<PyObject *> c_xd_vector_vector_double_descr).ob_type = <PyTypeObject *> PyArray_API[3]
c_xd_vector_vector_double_descr.typeobj = <PyTypeObject *> PyXD_VectorVectorDouble # typeobj
c_xd_vector_vector_double_descr.kind = 'x'  # kind, for xdress
c_xd_vector_vector_double_descr.type = 'x'  # type
c_xd_vector_vector_double_descr.byteorder = '='  # byteorder
c_xd_vector_vector_double_descr.flags = 0    # flags
c_xd_vector_vector_double_descr.type_num = 0    # type_num, assigned at registration
c_xd_vector_vector_double_descr.elsize = sizeof(cpp_vector[cpp_vector[double]])  # elsize, 
c_xd_vector_vector_double_descr.alignment = 8  # alignment
c_xd_vector_vector_double_descr.subarray = NULL  # subarray
c_xd_vector_vector_double_descr.fields = NULL  # fields
c_xd_vector_vector_double_descr.names = NULL
(<PyArray_Descr *> c_xd_vector_vector_double_descr).f = <PyArray_ArrFuncs *> &PyXD_VectorVectorDouble_ArrFuncs  # f == PyArray_ArrFuncs

cdef object xd_vector_vector_double_descr = <object> (<void *> c_xd_vector_vector_double_descr)
Py_INCREF(<object> xd_vector_vector_double_descr)
xd_vector_vector_double = xd_vector_vector_double_descr
cdef int xd_vector_vector_double_num = PyArray_RegisterDataType(c_xd_vector_vector_double_descr)
dtypes['vector_vector_double'] = xd_vector_vector_double
dtypes['xd_vector_vector_double'] = xd_vector_vector_double
dtypes[xd_vector_vector_double_num] = xd_vector_vector_double



