################################################
#                 WARNING!                     #
# This file has been auto-generated by xdress. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################


cimport dtypes
cimport numpy as np
from libcpp.vector cimport vector as cpp_vector
from pyne cimport cpp_endf2



cdef class endf_id:
    cdef void * _inst
    cdef public bint _free_inst
    pass





cdef class library:
    cdef void * _inst
    cdef public bint _free_inst
    pass





cdef class mt_base:
    cdef void * _inst
    cdef public bint _free_inst
    pass





cdef class mt_451(mt_base):
    cdef cpp_endf2.mt_451 * _subinst
    cdef cpp_endf2.mt_451 _ob
    cdef public np.ndarray _mt_list
    pass




{'cpppxd_footer': '', 'pyx_header': '', 'pxd_header': '', 'pxd_footer': '', 'cpppxd_header': '', 'pyx_footer': ''}
