################################################
#                 WARNING!                     #
# This file has been auto-generated by xdress. #
# Do not modify!!!                             #
#                                              #
#                                              #
#                    Come on, guys. I mean it! #
################################################


cimport dtypes
cimport numpy as np
cimport stlcontainers
from libcpp.utility cimport pair as cpp_pair
from libcpp.vector cimport vector as cpp_vector
from pyne cimport cpp_endf2



cdef class endf_id:
    cdef void * _inst
    cdef public bint _free_inst
    pass





cdef class library:
    cdef void * _inst
    cdef public bint _free_inst
    cdef public np.ndarray _content_list
    pass





cdef class mt_base:
    cdef void * _inst
    cdef public bint _free_inst
    pass





cdef class mt458_mf1(mt_base):
    cdef public np.ndarray _deb
    cdef public np.ndarray _defr
    cdef public np.ndarray _degd
    cdef public np.ndarray _degp
    cdef public np.ndarray _dend
    cdef public np.ndarray _denp
    cdef public np.ndarray _denu
    cdef public np.ndarray _der
    cdef public np.ndarray _det
    cdef public np.ndarray _eb
    cdef public np.ndarray _efr
    cdef public np.ndarray _egd
    cdef public np.ndarray _egp
    cdef public np.ndarray _end
    cdef public np.ndarray _enp
    cdef public np.ndarray _enu
    cdef public np.ndarray _er
    cdef public np.ndarray _et
    pass





cdef class mt457_mf8(mt_base):
    cdef public np.ndarray _eav
    cdef public np.ndarray _er
    cdef public np.ndarray _erel
    cdef public np.ndarray _fc
    cdef public np.ndarray _fd
    cdef public np.ndarray _lcon
    cdef public np.ndarray _nd
    cdef public np.ndarray _ner
    cdef public np.ndarray _ri
    cdef public np.ndarray _ricc
    cdef public np.ndarray _rick
    cdef public np.ndarray _ricl
    cdef public np.ndarray _ris
    cdef public np.ndarray _rtyp
    cdef public np.ndarray _styp
    cdef public np.ndarray _type
    pass





cdef class mt451(mt_base):
    cdef public np.ndarray _mt_list
    pass





cdef class mtfpy_mf8(mt_base):
    cdef public np.ndarray _e
    cdef public np.ndarray _i
    cdef public np.ndarray _yields
    pass





cdef class mt460_mf1(mt_base):
    cdef public np.ndarray _elist
    cdef public np.ndarray _intn
    cdef public np.ndarray _lambdas
    cdef public np.ndarray _nbt
    cdef public np.ndarray _t
    cdef public np.ndarray _tint
    pass





cdef class mt452_mf1(mt_base):
    cdef public np.ndarray _eint
    cdef public np.ndarray _intn
    cdef public np.ndarray _nbt
    cdef public np.ndarray _nu_e
    cdef public np.ndarray _poly
    pass





cdef class mt455_mf1(mt_base):
    cdef public np.ndarray _alpha_arr
    cdef public np.ndarray _eint
    cdef public np.ndarray _einti
    cdef public np.ndarray _intn
    cdef public np.ndarray _lambda_arr
    cdef public np.ndarray _lambdas
    cdef public np.ndarray _nbt
    cdef public np.ndarray _ne
    cdef public np.ndarray _nu_d
    pass





cdef class mt456_mf1(mt_base):
    cdef public np.ndarray _eint
    cdef public np.ndarray _intn
    cdef public np.ndarray _nbt
    cdef public np.ndarray _nu
    cdef public np.ndarray _nu_e
    pass




{'cpppxd_footer': '', 'pyx_header': '', 'pxd_header': '', 'pxd_footer': '', 'cpppxd_header': '', 'pyx_footer': ''}