#! /bin/bash
#
ifort -c -r8 -O1   ld.f90 
ifort -c -r8 -O1   invar.f90
ifort -c -r8 -O1   solvar.f90
ifort -c -r8 -O1   timevar.f90
ifort -c -r8 -O1   main.f90
ifort -c -r8 -O1   version.f90
ifort -c -r8 -O1   input.f90
ifort -c -r8 -O1   angle.f90
ifort -c -r8 -O1   readmt.f90
ifort -c -r8 -O1   readxs.f90
ifort -c -r8 -O1   readsrc.f90
ifort -c -r8 -O1   read_inflow.f90
ifort -c -r8 -O1   check.f90
ifort -c -r8 -O1   echo.f90
ifort -c -r8 -O1   solve.f90
ifort -c -r8 -O1   inner.f90
ifort -c -r8 -O1   sweep.f90
ifort -c -r8 -O1   output.f90
ifort -c -r8 -O1   output_phi.f90
ifort -r8 -O1   -o ../LD.exe *.o 
rm *.o *.mod
#ifort -c -r8   fluxsum.f90
#ifort -c -r8   qdrntflux.f90
#ifort -c -r8   p.f90
