#! /bin/bash
#
ifort -c -r8 -O2   ld.f90 
ifort -c -r8 -O2   invar.f90
ifort -c -r8 -O2   solvar.f90
ifort -c -r8 -O2   timevar.f90
ifort -c -r8 -O2   main.f90
ifort -c -r8 -O2   version.f90
ifort -c -r8 -O2   input.f90
ifort -c -r8 -O2   angle.f90
ifort -c -r8 -O2   readmt.f90
ifort -c -r8 -O2   readxs.f90
ifort -c -r8 -O2   readsrc.f90
ifort -c -r8 -O2   read_inflow.f90
ifort -c -r8 -O2   check.f90
ifort -c -r8 -O2   echo.f90
ifort -c -r8 -O2   solve.f90
ifort -c -r8 -O2   inner.f90
ifort -c -r8 -O2   sweep.f90
ifort -c -r8 -O2   output.f90
ifort -c -r8 -O2   output_phi.f90
ifort -r8 -O2   -o ../LD.exe *.o 
rm *.o *.mod
#ifort -c -r8   fluxsum.f90
#ifort -c -r8   qdrntflux.f90
#ifort -c -r8   p.f90
