import test_ahot
test_ahot.test_ahotn_ln_alternating()
print("ln alternating passed!")
test_ahot.test_ahotn_ln()
print("ln simple passed!")
test_ahot.test_ahotn_ll()
print("ll simple passed")
test_ahot.test_ahotn_nefd()
print("nefd simple passed")
test_ahot.test_dgfem_ld()
print("ld simple passed!")
test_ahot.test_dgfem_dense()
print("dense simple passed!")
test_ahot.test_dgfem_lagrange()
print("lagrange simple passed!")
test_ahot.test_sct_step()
print("sct-step simple passed!")
