#! /bin/bash

gfortran -fPIC -c invar.f90 solvar.f90 timevar.f90
gfortran -fPIC -c *.f90
rm main.o
f2py -m main -c *.o main.f90 -lblas -llapack
rm *.o
rm *.mod
#-L./blas/ =L./lapack/double/ -L./lapack/util -lmini_blas_s -lmini_lapack_util_s -lmini_lapack_D_s
#f2py -m main -c invar.o solvar.o main.f90 read_inflow.f90 readmt.f90 readxs.f90 readsrc.f90 check.f90 angle.f90 timevar.o solve.o inner_ahotn_l.o sweep.o ahotn_kernel_module.o output.f90

#-L./../../lapack_dependency/double/dgesv.f
