#! /bin/bash
#
gfortran -c -fdefault-real-8 precision_module.f90
gfortran -c -fdefault-real-8 geompack.f90
gfortran -c -fdefault-real-8 trackstruct.f90
gfortran -c -fdefault-real-8 igeompack.f90
gfortran -c -fdefault-real-8 trackroutines.f90
gfortran -c -fdefault-real-8 sct_module.f90
gfortran -c -fdefault-real-8 invar.f90
gfortran -c solvar.f90
gfortran -c kernel_module.f90
gfortran -c timevar.f90
gfortran -c main.f90
gfortran -c version.f90
gfortran -c input.f90
gfortran -c angle.f90
gfortran -c readmt.f90
gfortran -c readxs.f90
gfortran -c readsrc.f90
gfortran -c read_inflow.f90
gfortran -c check.f90
gfortran -c echo.f90
gfortran -c solve.f90
gfortran -c inner.f90
gfortran -c sweep.f90
gfortran -c output.f90
gfortran -c output_phi.f90
gfortran -o ../ahotn0-sct.exe *.o 
rm *.o *.mod
