#! /bin/bash
#
ifort -c -r8 -g -traceback -check all -fpe0  precision_module.f90
ifort -c -r8 -g -traceback -check all -fpe0  geompack.f90
ifort -c -r8 -g -traceback -check all -fpe0  trackstruct.f90
ifort -c -r8 -g -traceback -check all -fpe0  igeompack.f90
ifort -c -r8 -g -traceback -check all -fpe0  trackroutines.f90
ifort -c -r8 -g -traceback -check all -fpe0  sct_module.f90
ifort -c -r8 -g -traceback -check all -fpe0 invar.f90
ifort -c -r8 -g -traceback -check all -fpe0 solvar.f90
ifort -c -r8 -g -traceback -check all -fpe0 kernel_module.f90
ifort -c -r8 -g -traceback -check all -fpe0 timevar.f90
ifort -c -r8 -g -traceback -check all -fpe0 main.f90
ifort -c -r8 -g -traceback -check all -fpe0 version.f90
ifort -c -r8 -g -traceback -check all -fpe0 input.f90
ifort -c -r8 -g -traceback -check all -fpe0 angle.f90
ifort -c -r8 -g -traceback -check all -fpe0 readmt.f90
ifort -c -r8 -g -traceback -check all -fpe0 readxs.f90
ifort -c -r8 -g -traceback -check all -fpe0 readsrc.f90
ifort -c -r8 -g -traceback -check all -fpe0 read_inflow.f90
ifort -c -r8 -g -traceback -check all -fpe0 check.f90
ifort -c -r8 -g -traceback -check all -fpe0 echo.f90
ifort -c -r8 -g -traceback -check all -fpe0 solve.f90
ifort -c -r8 -g -traceback -check all -fpe0 inner.f90
ifort -c -r8 -g -traceback -check all -fpe0 sweep.f90
ifort -c -r8 -g -traceback -check all -fpe0 output.f90
ifort -c -r8 -g -traceback -check all -fpe0 output_phi.f90
ifort -o ../ahotn0-sct.exe *.o 
rm *.o *.mod
