name: Build wheels

on:
  # allows running workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - develop
    paths-ignore:
      - docs/**

  push:
    branches:
      - scikit-build-core
    paths-ignore:
      - docs/**

jobs:
  main:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: manylinux_x86_64
          - os: macos-13
            arch: macosx_x86_64
          - os: macos-14
            arch: macosx_arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.0
        env:
          CIBW_BUILD: "cp*-${{ matrix.arch }}"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_ARCHS_MACOS: "native"
          CIBW_BEFORE_BUILD_MACOS: |
            brew install hdf5
          CIBW_ENVIRONMENT_MACOS: >
            SKBUILD_DOWNLOAD_LAPACK=OFF
            CMAKE_Fortran_COMPILER=gfortran-14
          CIBW_BUILD_FRONTEND: "build"
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
