name: Quick Wheel test

on:
  # allows running workflows manually
  workflow_dispatch:
  push:
    paths-ignore:
      - 'docs/*'
      - 'examples/*'
      - 'img/*'
      - 'news/*'
      - 'tutorial/*'
      - './*.rst'
      - 'license.txt'
      - 'PULL_REQUEST_TEMPLATE.md'

jobs:
  main:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]

    steps:
      - name: Additional macOS settings
        if: matrix.os == 'macos-13' || matrix.os == 'macos-14'
        shell: bash -l {0}
        run: |
          # hdf5 is needed for building tables
          brew install gcc hdf5
          # ISSUE: DYLD_LIBRARY_PATH for gcc is not set on Intel macOS
          echo "DYLD_LIBRARY_PATH=/usr/local/opt/gcc/lib/gcc/current/:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=${{ matrix.os == 'macos-14' && '14.0' || '13.0' }}" >> $GITHUB_ENV
          echo "FC=gfortran-14" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build wheels
        shell: bash -l {0}
        run: |
          pip install build
          python -m build --wheel
      - name: Fix wheels for macOS
        if: matrix.os == 'macos-13' || matrix.os == 'macos-14'
        shell: bash -l {0}
        run: |
          pip install delocate
          for whl in dist/*.whl; do
            delocate-wheel -v $whl
          done
      - name: Install PyNE
        shell: bash -l {0}
        run: |
          pip install -vvv dist/pyne*.whl
      - name: Nuc data make
        shell: bash -l {0}
        run: |
          nuc_data_make
      - name: Test PyNE
        shell: bash -l {0}
        run: |
          cd tests
          pip install pytest
          pytest -ra
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels for ${{ matrix.os }}
          path: dist
