name: Quick Wheel test

on:
  # allows running workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - develop
    paths-ignore:
      - docs/**

  push:
    branches:
      - scikit-build-core
    paths-ignore:
      - docs/**

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build wheels
        shell: bash -l {0}
        run: |
          pip install build
          python -m build --wheel

      - name: Install PyNE
        shell: bash -l {0}
        run: |
          pip install dist/pyne*.whl

      - name: Nuc data make
        shell: bash -l {0}
        run: |
          nuc_data_make

      - name: Test PyNE 
        shell: bash -l {0}
        run: |
          cd tests
          pip3 install pytest
          pytest -ra
