name: Quick Wheel test

on:
  # allows running workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - develop
    paths-ignore:
      - docs/**

  push:
    branches:
      - develop
    paths-ignore:
      - docs/**

jobs:
  main:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install hdf5 Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran libblas-dev liblapack-dev libeigen3-dev libhdf5-dev hdf5-tools
          # hdf5 std directory
          export HDF5_ROOT=/usr/lib/x86_64-linux-gnu/hdf5/serial
          export LD_LIBRARY_PATH="${HDF5_ROOT}:$GITHUB_WORKSPACE/lib"
        if: matrix.os == 'ubuntu-latest'

      - name: Install Miniconda Windows
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
        if: matrix.os == 'windows-latest'

      - name: Install Python Packages
        run: |
          python -m pip install wheel
          python -m pip install "cython<3" numpy build pytest

      - name: Install hdf5 Windows
        run: |
          conda install curl eigen
          conda install -c conda-forge hdf5
          conda remove -y yaml-cpp
          Add-Content -Path $env:GITHUB_ENV -Value "HOME_PATH=$env:GITHUB_WORKSPACE\.."
          Add-Content -Path $env:GITHUB_ENV -Value "CONDA_LOC=C:\Miniconda\Library"
          Add-Content -Path $env:GITHUB_ENV -Value "EIGEN3_DIR=C:\Miniconda\Library\"
        if: matrix.os == 'windows-latest'

      - name: Install hdf5 MacOS
        shell: bash -l {0}
        run: |
          brew install hdf5 eigen
          echo "HOME=$GITHUB_WORKSPACE/.." >> $GITHUB_ENV
          echo "HDF5_ROOT=$HDF5_PATH" >> $GITHUB_ENV
        if: matrix.os == 'macos-latest'

      - name: Install MOAB Ubuntu
        run: |
          cd $GITHUB_WORKSPACE
          # clone and version
          git clone --depth 1 https://bitbucket.org/fathomteam/moab -b 5.3.0
          cd moab
          mkdir -p build
          cd build
          # cmake, build and install
            cmake ../ -DENABLE_HDF5=ON \
              -DHDF5_ROOT=$HDF5_ROOT \
              -DBUILD_SHARED_LIBS=ON \
              -DENABLE_PYMOAB=ON \
              -DENABLE_BLASLAPACK=OFF \
              -DENABLE_FORTRAN=OFF \
              -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE
            make
            make install
          cd $GITHUB_WORKSPACE
          rm -rf $GITHUB_WORKSPACE/moab
          export MOAB_ROOT=$GITHUB_WORKSPACE
          echo "MOAB installed"
        if: matrix.os == 'ubuntu-latest'

      - name: Install MOAB Windows
        run: |
          Set-Location $Env:GITHUB_WORKSPACE
          # clone and version
          git clone --depth 1 https://bitbucket.org/fathomteam/moab -b 5.3.0
          Set-Location moab
          New-Item -ItemType Directory -Force -Path build
          Set-Location build
          # cmake, build, and install
          cmake ../ -G "Visual Studio 17 2022" `
            -DCMAKE_INSTALL_PREFIX="$Env:GITHUB_WORKSPACE" `
            -DCMAKE_EXE_LINKER_FLAGS="/std:c++latest -DH5_BUILT_AS_DYNAMIC_LIB" `
            -DCMAKE_MODULE_LINKER_FLAGS="/std:c++latest" `
            -DCMAKE_SHARED_LINKER_FLAGS="/std:c++latest" `
            -DCMAKE_STATIC_LINKER_FLAGS="" `
            -DENABLE_HDF5=ON `
            -DHDF5_ROOT="$Env:CONDA_LOC" `
            -DBUILD_SHARED_LIBS=ON `
            -DENABLE_PYMOAB=ON `
            -DENABLE_IMESH=OFF `
            -DENABLE_TESTING=OFF `
            -DENABLE_BLASLAPACK=OFF `
            -DENABLE_FORTRAN=OFF `
            -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          cmake --install .
          Set-Location $Env:GITHUB_WORKSPACE
          Remove-Item -Force -Recurse moab
          $Env:MOAB_ROOT = "$Env:GITHUB_WORKSPACE"
          Write-Host "MOAB installed"
        if: matrix.os == 'windows-latest'

      - name: Install DAGMC Ubuntu
        run: |
          cd $GITHUB_WORKSPACE
          # clone the repository
          git clone https://github.com/ahnaf-tahmid-chowdhury/DAGMC.git dagmc
          cd dagmc
          mkdir -p build
          cd build
          # cmake, build and install
          cmake ../ -DMOAB_CMAKE_CONFIG=$GITHUB_WORKSPACE/lib/cmake/MOAB \
            -DMOAB_DIR=$GITHUB_WORKSPACE \
            -DBUILD_STATIC_LIBS=OFF \
            -DBUILD_TALLY=ON \
            -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE
          make
          make install
          cd $GITHUB_WORKSPACE
          rm -rf "$GITHUB_WORKSPACE/dagmc"
          export DAGMC_ROOT=$GITHUB_WORKSPACE
          echo "DAGMC installed"
        if: matrix.os == 'ubuntu-latest'

      - name: Install DAGMC Windows
        run: |
          Set-Location $Env:GITHUB_WORKSPACE
          # clone the repository
          git clone https://github.com/ahnaf-tahmid-chowdhury/DAGMC.git dagmc
          Set-Location dagmc
          New-Item -ItemType Directory -Force -Path build
          Set-Location build
          # cmake, build, and install
          cmake ../ -DMOAB_CMAKE_CONFIG=$Env:GITHUB_WORKSPACE\lib\cmake\MOAB `
            -DMOAB_DIR=$Env:GITHUB_WORKSPACE `
            -DBUILD_STATIC_LIBS=OFF `
            -DBUILD_TALLY=ON `
            -DCMAKE_INSTALL_PREFIX=$Env:GITHUB_WORKSPACE
          cmake --build . --config Release
          cmake --install .
          Set-Location $Env:GITHUB_WORKSPACE
          Remove-Item -Force -Recurse "dagmc"
          $Env:DAGMC_ROOT = "$Env:GITHUB_WORKSPACE"
          Write-Host "DAGMC installed"
        if: matrix.os == 'windows-latest'

      - name: Checkout PyNE
        uses: actions/checkout@v3

      - name: Build wheels
        run: |
          python -m build --wheel

      - name: Install PyNE
        run: |
          python -m pip install dist/pyne*.whl
          nuc_data_make

      - name: Test PyNE
        run: |
          cd tests
          pytest -ra ../tests
