name: Quick Wheel test

on:
  # allows running workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - develop
    paths-ignore:
      - docs/**

  push:
    branches:
      - scikit-build-core
    paths-ignore:
      - docs/**

jobs:
  main:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]

    steps:
      - name: Additional macOS settings
        if: matrix.os == 'macos-*'
        shell: bash -l {0}
        run: |
          echo "FC=$(which gfortran-14)" >> $GITHUB_ENV
          # hdf5 is needed for building tables
          brew install hdf5
          # ISSUE: DYLD_LIBRARY_PATH for 14.1 on Intel macOS
          echo "DYLD_LIBRARY_PATH=/usr/local/Cellar/gcc/14.1.0/lib/gcc/current/:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build wheels
        shell: bash -l {0}
        run: |
          pip install build
          python -m build --wheel

      - name: Fix wheels
        if : matrix.os == 'macos-*' 
        shell: bash -l {0}
        run: |
          pip install delocate
          for whl in dist/*.whl; do
            delocate repair $whl
          done

      - name: Install PyNE
        shell: bash -l {0}
        run: |
          pip install dist/pyne*.whl

      - name: Nuc data make
        shell: bash -l {0}
        run: |
          nuc_data_make

      - name: Test PyNE 
        shell: bash -l {0}
        run: |
          cd tests
          pip install pytest
          pytest -ra

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels for ${{ matrix.os }}
          path: dist